### PR TITLE
Add some missing Behavior instances (fixes #34)

### LINKED ISSUE #34: Add Num instance for Behavior
Since GHC 7.4.1 `Eq` and `Show` are no longer superclasses of `Num`.

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Num, Floating, Fractional, IsString

### CODE REVIEW

**Comment by ocharles** [comment]
This is https://github.com/HeinrichApfelmus/reactive-banana/issues/34, and I think we still need to reach an agreement there.

**Comment by mitchellwrosen** [comment]
Indeed, I just decided to throw up a patch in case consensus is reached :)

**Comment by HeinrichApfelmus** [comment]
Hm, yes, ok, let's do this. :smile: Can you add an entry to the changelog? I'm forgot the PVP here, does adding a class instance force a change of the major version?

**Comment by ocharles** [comment]
This is only a minor version bump. As per https://pvp.haskell.org/:

> Non-breaking change. Otherwise, if only new bindings, types, classes, **non-orphan instances** ...

**Comment by HeinrichApfelmus** [comment]
Thanks!

**Pull request merged**
