### PR TITLE
Fix performance benchmark

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch gets `Reactive.Banana.Test.Performance` compiling again.

I'm not certain I did the translation correctly - I haven't used pre-1.0 reactive-banana before, and the types were not so straightforward :sweat_smile: 

Is this the correct output?

```
021011111010012111010021023311004003001021112200022010001131121101120003003040000232122011100222001000121001122101000122212200002123103230031210101301020312000110001120120110110100112311201121011100102111003200312120200213001112120111213102000001012001121010002030010121011111210323020001121130100103
```

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Whoops, no, this is the correct output:

```
09758612101117715913201523921202324272132371829363521412637344029513027564133355048545239585450545556514954496055565985567062694756577268687971788068697989958482103928996811041048310396101100106939595959698999999100101103105106106107107107107108110112114115117119119119119119121122124127128128131133136136136139140142143143144144145148148149149151151154155157157157157158159159159159160161163163164166166167168168169170170171171171172173175178179180182182183184186187187188189190190190191191193194195196196196199201201201204205207208210210212212212214215218218218219220221223224226226227228229231232235236236238238238238238238239239240242242242243244246247247248248248248250250253253253254254255257258258259260261262263265266266269271274274276276276276277278280281282285285286286286287287290
```

Hrm..

**Comment by mitchellwrosen** [comment]
Ok, this is fixed now

**Comment by mitchellwrosen** [comment]
Merging!

**Comment by HeinrichApfelmus** [comment]
Thanks, Mitchell! 😊

**Pull request merged**
