### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by gelisam**

### CODE REVIEW

**Comment by gelisam** [comment]
As I am reading the code to understand why my other pull request is not the correct fix, I have encountered a few functions which are not used anymore.

**Comment by HeinrichApfelmus** [comment]
The first change sounds good to me, but removing `traverseDependencies` is probably not a good idea — it certainly isn't used anyway, but I consider part of the specification of how the data structure is supposed to work.

**Comment by gelisam** [comment]
Okay, I have removed the second commit from the pull request.

**Comment by HeinrichApfelmus** [comment]
With the release of version 0.9, this particular pull request is now obsolete. But thanks again for your help!

**Pull request closed without merging**
