### PR TITLE
Release 1.2.2.0

### PR DESCRIPTION
**Pull request by ocharles**
Fixes https://github.com/HeinrichApfelmus/reactive-banana/issues/215

### CODE REVIEW

**Comment by ocharles** [comment]
@mitchellwrosen It's been a long time since we last released, and right now we've got all sorts of bound violations. I think we should get a new release out! What do you think? I'm tempted to say we get a resolution to https://github.com/HeinrichApfelmus/reactive-banana/issues/203 in for this release too. If you agree, I'll chime in with thoughts there.

**Comment by mitchellwrosen** [comment]
Sounds good to me!

My thoughts, fwiw, are to go with your preferred version of mergeWith, as we could always generalize with the added dep(s) later.

**Comment by ocharles** [comment]
Let's wait for https://github.com/HeinrichApfelmus/reactive-banana/pull/220, then release.

**Comment by ocharles** [comment]
@HeinrichApfelmus I think we're good to go here! Happy for me to merge, tag and push to Hackage?

**Review by HeinrichApfelmus — APPROVED** [review]
> Happy for me to merge, tag and push to Hackage?

Happy indeed! Thank you, @ocharles and @mitchellwrosen !

**Comment by ocharles** [comment]
[Released](https://hackage.haskell.org/package/reactive-banana-1.2.2.0) :partying_face:

**Pull request merged**
