### PR TITLE
Allow pqueue-1.5

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Hi, thanks, any other info? Have you looked at the changeling of the new version and confirmed the bump is safe, or is this PR just to get the conversation started?

**Comment by Bodigrim** [comment]
I did, but you don't have to rely on my word only: the CI is green.

**Comment by mitchellwrosen** [comment]
For sure. The type checker isn't always able to detect incompatibilities, so for bumps like this it helps to know a human has poked around the changelogs. Ok, thanks for the contribution!

**Comment by Bodigrim** [comment]
@mitchellwrosen could you possibly please make a Hackage revision?

**Comment by mitchellwrosen** [comment]
@Bodigrim done 👍

**Pull request merged**
